spring:
    web:
        locale-resoler: fixed
        locale: pt_BR
    mvc:
        format:
            date-time: iso

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/ms_user?useSSL=false&allowPublicKeyRetrieval=true}
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}