spring:
    web:
        locale-resoler: fixed
        locale: pt_BR
    mvc:
        format:
            date-time: iso

    datasource:
        url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/ms_user?useSSL=false&allowPublicKeyRetrieval=true}
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
            show_sql: false